module "instance-creation" {
  source = "../Day-7-module-source-temp"       # PATH TO YOUR MODULE SOURCE WHERE TEMPLATE IS DEFINED

  ami = "ami-08a6efd148b1f7504"                # AMI ID INSERTION IN THE TEMPLATE FIRST THIS VALUE GOES TO VARIABLES.TF FILE THE IN MAIN FILE AND EXECUTE
  instance_type = "t2.micro"                   # INSTANCE TYPE INSERTION IN THE TEMPLATE FIRST THIS VALUE GOES TO VARIABLES.TF FILE THE IN MAIN FILE AND EXECUTE
  instance-name = "my-ec2"                     # INSTANCE NAME INSERTION IN THE TEMPLATE FIRST THIS VALUE GOES TO VARIABLES.TF FILE THE IN MAIN FILE AND EXECUTE
}